version:  '3'
services:
  datascience-notebook:
      build: .
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work
      ports:
        - ${PORT}:8888
      container_name:   jupyter_notebook
      command: "start-notebook.sh "